import type { Metadata } from "next";
import './style.css'
import Content from "./components/Content";


export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <div>
         <Content>
            {children}
         </Content>
      </div>
   );
}
